name: skills_taxonomy
version: "0.1.0"
config-version: 2
profile: skills_taxonomy

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

clean-targets: ["target", "dbt_packages"]

models:
  skills_taxonomy:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

seeds:
  skills_taxonomy:
    +schema: seeds
